x;
2;
true;
"hello";
();
x + 3;
x - 2 + 3;
not true;
x = 2;
x <= 10;
1; 2; 3;
x + 1; y + 2; z + 3;
let x = 1 in x; 2;
fun x -> x + 2;
fun x -> fun y -> x + y;
fun x -> if x = 0 then 1 else x;
if true then 1 else 2;
if x < 10 then x + 1 else x - 1;
if x = 0 then if y = 0 then 1 else 2 else 3;
if not (x = 0) then 100 else 200;
let x = 2 in x;
let x = 2 + 3 in x + 2;
let rec f = fun x -> x in f;
let x = 1 in let y = 2 in x + y;
let x = if true then 1 else 2 in x + 10;
let x = 1 in x + 2; 3;
if x = 1 && y = 2 || not z then 10 else 20;
(fun x -> x + 1);
let f = fun x -> x + 1 in f